### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by xfisbest** [voidtemp/OpenXStreamLoader#5] opened 2020-09-24 05:19 UTC
hello i just found and downloaded openxstreamloader, it's great! but the issue im getting is that im getting frames skipping, i mean like (if someone is has gone away from cam we cannot see him/her coming back, just see him sitting in front again) i mean the frames get skipped, the recorder records like 00:01:03 00:01:06 00:01:09 and sometimes takes (more than 6-7 seconds but still records 3 seconds time. the internet is of 8Mbps. i only record 720p

**Comment by rz1a** [comment] 2020-09-24 06:10
I have exactly the same problem. Except my speed is 600 Mbps

**Comment by xfisbest** [comment] 2020-09-24 06:24
i only record 1 stream and only 1 in favourite

**Comment by voidtemp** [comment] 2020-09-24 12:09
600 Mbps - that's impressive.

I don't think I can help here unfortunately. All stream recording is done by Streamlink, it runs as independent process on computer, OpenXSteamLoader acts only as GUI interface for it. So possibly there are some issues with Streamlink itself.
You can try to increase timeouts in its parameters string o Settings tab. Please refer to 
https://streamlink.github.io/cli.html#cmdoption-hls-timeout

From my experience lags may happen for different reasons:
- your current connection actual bandwidth is lower than declared by your ISP
- server lags under high load
- lags on model side: I had noticed that some rooms may hang for a while when watching in browser and model is trying to reconnect.

Streams are delivered in small chunks like 2 to 10 seconds in duration. And those chunks live for a quite short amount of time on server. So if lag occurs longer than such timeout then chunk is lost irrecoverably.

**Comment by voidtemp** [comment] 2020-09-24 12:27
**xfisbest**,
btw 720p@60fps may take up to 5000kbps or more. So in case 8Mbps is a theoretical maximum real connection can have less upper limit. Especially if you're watching video online simultaneously or downloading something etc.

**Comment by xfisbest** [comment] 2020-09-24 12:43
can't it be 720@20 fps..? because my laptop is 1440 display if i do less quality pixel will be disturbed.

**Comment by xfisbest** [comment] 2020-09-24 12:44
i mean live stream also works 1080p mostly great but 720p is smooth but recording got lags :/

**Comment by voidtemp** [comment] 2020-09-24 12:56
Do you experience those lags every time you record?
Can you please try this site https://speedof.me/

**Comment by xfisbest** [comment] 2020-09-24 13:37
here you go bruh! https://i.speedof.me/200924133725-838

**Comment by xfisbest** [comment] 2020-09-24 13:38
yes i experience lag everytime

**Comment by xfisbest** [comment] 2020-09-24 14:03
even with less quality i mean 420p, just a question is there anything else i need to make this properly work like install java or python something? because i just installed windows 1 month back so it's most likely new .

**Comment by rz1a** [comment] 2020-09-24 14:47
I've lowered the quality to 480p but there is lag still, but ocurs less often. 

When i said my number of streams and favorites was to know if it's possible the lag is due to having a big amount of recordings and online checking at same time or is not related at all?

**Comment by voidtemp** [comment] 2020-09-24 15:14
@xfisbest 
with that Internet connection I wouldn't expect much honestly.

You can try to run Streamlink from command line:
```Streamlink.exe  --loglevel debug --ffmpeg-verbose --hls-timeout 120 --hls-playlist-reload-attempts 20 --hls-segment-timeout 90 --hds-segment-threads 8 --hls-segment-threads 8 --hds-timeout 120 --hds-segment-timeout 90 --hds-segment-attempts 20 -o "output_file_name.ts" -f https://url/ 720p"```

This will totally exclude OpenXStreamLoader as a middleman.

@rz1a 
Additionally to suggestion above to start streams recording directly from command line we can try to exclude possible interference of online check requests: input some big number in "Interval between each individual request to server". Like 500000. This will literally turn off any status updates.

**Comment by voidtemp** [comment] 2020-09-24 15:21
Btw if you right click on a task on Record tab there is   menu item "Streamlink output".
What you might see there is messages about chunks were dropped by time out.

**Comment by xfisbest** [comment] 2020-09-24 16:58
https://i.speedof.me/200924165529-898 
But **Streams** work perfect even on 1080p smoothly

**Comment by xfisbest** [comment] 2020-09-24 16:58
and where to type this command?

**Comment by voidtemp** [comment] 2020-09-24 17:23
In folder "Streamlink_Portable" Shift+right_click on empty space, there will be "Open command window" menu.

**Comment by xfisbest** [comment] 2020-09-25 11:11
with command line it works perfect! i mean not even 1 second frame drop! perfect! just the issue is file size is big enough! i mean 1hour 26 minutes have 1.83Gb file size, and also consuming more internet bandwidth

**Comment by xfisbest** [comment] 2020-09-25 12:54
command line recorder works great! perfect! but now i can see a 1:28 hour as 1.9gb so big!

**Comment by voidtemp** [comment] 2020-09-25 12:59
I can't imagine how to repeatably reproduce it. I mean I was recording up to 10 1080p streams same time and didn't notice such a problem, just once or twice. Although I don't watch through all the records because it's hours of material.

Can you try to disable online check by "input some big number in "Interval between each individual request to server" as I mentioned above?

Also I check and report file size each 3 seconds, but I don't think it's the problem.

**Comment by xfisbest** [comment] 2020-09-25 13:15
it's also taking alot bandwidth like im streaming too, i mean for a 1.3 hour stream it takes 700Mb or more of my internet

**Comment by xfisbest** [comment] 2020-09-25 13:21
the value is 120 currently of me but default is 60 how much should i do then?

**Comment by xfisbest** [comment] 2020-09-25 13:22
default value is 60 and mine is 120 i should make it 540 or something more bigger?

**Comment by voidtemp** [comment] 2020-09-25 14:02
No, it's first one - "Interval between each individual request to server", in milliseconds.

**Comment by voidtemp** [comment] 2020-09-25 14:04
However other two will do the job too, if set them before adding a task.

**Comment by xfisbest** [comment] 2020-09-25 14:14
im currently using this:
Streamlink.exe --loglevel debug --ffmpeg-verbose --hls-timeout 540 --hls-playlist-reload-attempts 20 --hls-segment-timeout 90 --hds-segment-threads 8 --hls-segment-threads 8 --hds-timeout 120 --hds-segment-timeout 90 --hds-segment-attempts 20 -o "output_file_name.ts" -f https://url 720p"

**Comment by voidtemp** [comment] 2020-09-25 14:42
I meant OpenXStreamLoader options on Settings tab. To verify whether it really causes the problem or the problem is just some random event.

**Comment by xfisbest** [comment] 2020-09-25 18:05
i just changed request to server value in command and in the input box and now everything great! Thanks bruh!

**Comment by voidtemp** [comment] 2020-09-25 18:11
That's great!
What value it initially was and what did you enter?
Also can you please do a small test: restore your initial value and see whether the problem comes back again. Because for me it sounds like there is still some randomness in this whole situation.

**Comment by xfisbest** [comment] 2020-09-30 12:14
the values i did was 542 in command and in box it was 4000, i tried defaults too now, but issue is that it doesn't start recording after waiting status i mean when broadcaster come back the recorder only shows timer of how much recorded but file size still -1Byte which means its not getting recorded even in the folder it was empty nothing recorded the stream recorded was of almost 6-7 hours on 480p

**Comment by voidtemp** [comment] 2021-01-26 03:15
Hello!

Is this issue still relevant?
If no then please close it.

**Closed** 2021-01-26 03:48 UTC
